"""update_summary_model_and_constraints

Revision ID: 58bdbdba3bb3
Revises: 3b59c85d070d
Create Date: 2026-03-12 12:28:27.827353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58bdbdba3bb3'
down_revision: Union[str, None] = '3b59c85d070d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('source_id', sa.UUID(), nullable=True))
    op.add_column('summaries', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'summaries', ['source_id'])
    op.drop_constraint('summaries_article_id_fkey', 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'raw_articles', ['source_id'], ['id'])
    op.drop_column('summaries', 'article_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.create_foreign_key('summaries_article_id_fkey', 'summaries', 'raw_articles', ['article_id'], ['id'])
    op.drop_constraint(None, 'summaries', type_='unique')
    op.drop_column('summaries', 'metadata')
    op.drop_column('summaries', 'source_id')
    # ### end Alembic commands ###
