"""change rel float

Revision ID: d34b7f46de0e
Revises: d9ae3b2057f3
Create Date: 2026-03-12 15:59:26.560761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd34b7f46de0e'
down_revision: Union[str, None] = 'd9ae3b2057f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_usage', 'key_index',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('raw_articles', 'relevance_score',
               existing_type=sa.SMALLINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('summaries', 'relevance_score',
               existing_type=sa.SMALLINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summaries', 'relevance_score',
               existing_type=sa.Float(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('raw_articles', 'relevance_score',
               existing_type=sa.Float(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('key_usage', 'key_index',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
