"""add is_urgent

Revision ID: d9ae3b2057f3
Revises: 58bdbdba3bb3
Create Date: 2026-03-12 14:29:59.476353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd9ae3b2057f3'
down_revision: Union[str, None] = '58bdbdba3bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_articles', sa.Column('is_urgent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_articles', 'is_urgent')
    # ### end Alembic commands ###
